# Generated by Django 5.0.6 on 2025-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_rename_issue_choices_issue_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='issue_attachments/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Administrative', 'Administrative'), ('Technical', 'Technical')], default='Academic', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=100),
        ),
    ]
