# Generated by Django 5.0.6 on 2025-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_attached_file_issue_category_issue_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Missing Marks', 'Missing Marks'), ('Appeals', 'Appeals'), ('Corrections.', 'Corrections.')], default='Academic', max_length=100),
        ),
    ]
